#! /bin/sh
# Author: Momen

echo -n "s98lddmodules: Number of args: "
echo $#

if [ $# -ne 1 ]; then
    echo "s98lddmodules: Error, Arguments are not equal 1!"
    exit 1
fi

mode_w=$1

case $mode_w in
    start)
        echo "Loading modules"
        cd /lib/modules/5.15.18/extra
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading modules"
        scull_unload
        module_unload faulty 
        rmmod hello
        ;;
    *)
        echo "Invalid option!"
    exit 1
esac

exit 0